name: Nightly Test Run

on:
  schedule:
    - cron: '0 0 * * *' # Запуск каждый день в полночь (UTC)
  workflow_dispatch: # Возможность запуска вручную через интерфейс GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '22'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install latest ChromeDriver
        run: |
          CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d $HOME/bin
          rm chromedriver_linux64.zip
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Install Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Start Xvfb
        run: |
          Xvfb :99 -ac &

      - name: Verify Chrome and ChromeDriver
        run: |
          echo "Chrome version:"
          google-chrome --version
          echo "ChromeDriver version:"
          chromedriver --version

      - name: Set up environment variables
        run: echo "export ENV_VAR=value" >> $GITHUB_ENV

      - name: Build and test with Gradle
        run: |
          DISPLAY=:99.0 ./gradlew test --no-daemon
        env:
          DISPLAY: :99.0

      - name: Publish test results
        if: always()  # Это позволит выполнить шаг даже если тесты не прошли
        run: |
          echo "Test results:"
          cat build/reports/tests/test/index.html  # Вывод отчета о тестах