name: Nightly Test Run

on:
  schedule:
    - cron: '0 0 * * *' # Запуск каждый день в полночь (UTC)
  workflow_dispatch: # Возможность запуска вручную через интерфейс GitHub
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '22'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install latest ChromeDriver
        run: |
          # Скачиваем последнюю версию ChromeDriver
          CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d $HOME/bin
          rm chromedriver_linux64.zip

          # Добавляем ChromeDriver в PATH
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Verify Chrome and ChromeDriver
        run: |
          google-chrome --version
          chromedriver --version

      - name: Build and test with Gradle
        run: ./gradlew test --no-daemon
